[package]
name = "rendering_util"
version = "0.1.2"
authors = ["Chay Nabors"]
edition = "2021"
description = "Some simple utils for wgpu code."
resolver = "2"

[dependencies]
log = "0.4.14"
raw-window-handle = "0.4.2"
wgpu = "0.12.0"
